# Render deployment configuration for OpenManus
# This file defines the infrastructure and services for Render deployment

services:
  # Main OpenManus web service
  - type: web
    name: openmanus-api
    env: docker
    dockerfilePath: ./Dockerfile.improved
    dockerContext: .
    dockerTarget: render
    plan: standard
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        fromService:
          type: web
          name: openmanus-api
          property: port
      - key: DATABASE_URL
        fromDatabase:
          name: openmanus-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: openmanus-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: OPENROUTER_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: ANTHROPIC_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: RENDER
        value: true
      - key: HEADLESS_BROWSER
        value: true
      - key: CORS_ORIGINS
        value: "*"
      - key: LOG_LEVEL
        value: INFO
      - key: WORKERS
        value: 2
    buildCommand: |
      echo "Building OpenManus for Render..."
      pip install --upgrade pip
    startCommand: |
      python -m uvicorn app.api:app --host 0.0.0.0 --port $PORT --workers 2

  # MCP server service
  - type: web
    name: openmanus-mcp
    env: docker
    dockerfilePath: ./Dockerfile.improved
    dockerContext: .
    dockerTarget: render
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /mcp/health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: MCP_SERVER_PORT
        fromService:
          type: web
          name: openmanus-mcp
          property: port
      - key: REDIS_URL
        fromService:
          type: redis
          name: openmanus-redis
          property: connectionString
    startCommand: |
      python run_mcp_server.py --port $PORT

  # Background worker service
  - type: worker
    name: openmanus-worker
    env: docker
    dockerfilePath: ./Dockerfile.improved
    dockerContext: .
    dockerTarget: render
    plan: starter
    region: oregon
    branch: main
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: openmanus-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: openmanus-redis
          property: connectionString
    startCommand: |
      python -m app.worker

databases:
  # PostgreSQL database
  - name: openmanus-postgres
    databaseName: openmanus
    user: openmanus
    plan: starter
    region: oregon
    postgresMajorVersion: 15

  # Redis cache
  - name: openmanus-redis
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys-lru

# Environment groups for shared configuration
envVarGroups:
  - name: openmanus-common
    envVars:
      - key: APP_NAME
        value: OpenManus
      - key: APP_VERSION
        value: 2.0.0
      - key: STREAM_CALLBACKS_ENABLED
        value: true
      - key: HUMAN_CALLBACKS_ENABLED
        value: true
      - key: PLANNING_ENABLED
        value: true
      - key: REPLANNING_ENABLED
        value: true
      - key: MCP_TOOLS_ENABLED
        value: true
      - key: ENABLE_CHAT_API
        value: true
      - key: ENABLE_WEB_INTERFACE
        value: true
      - key: ENABLE_WEBSOCKETS
        value: true
      - key: ENABLE_MULTI_AGENT
        value: true
      - key: HEALTH_CHECK_ENABLED
        value: true
      - key: METRICS_ENABLED
        value: true

